/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as FairPlayRouteImport } from './routes/fair-play'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as VariantsRouteImport } from './routes/variants'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as LearnIdRouteImport } from './routes/learn.$id'
import { Route as PuzzlesIdRouteImport } from './routes/puzzles.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const FairPlayRoute = FairPlayRouteImport.update({
  id: '/fair-play',
  path: '/fair-play',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const LearnIdRoute = LearnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LearnRoute,
} as any)
const PuzzlesIdRoute = PuzzlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PuzzlesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/fair-play': typeof FairPlayRoute
  '/history': typeof HistoryRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/variants': typeof VariantsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/history/$id': typeof HistoryIdRoute
  '/learn/$id': typeof LearnIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/fair-play': typeof FairPlayRoute
  '/history': typeof HistoryRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/variants': typeof VariantsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/history/$id': typeof HistoryIdRoute
  '/learn/$id': typeof LearnIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/fair-play': typeof FairPlayRoute
  '/history': typeof HistoryRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/variants': typeof VariantsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/history/$id': typeof HistoryIdRoute
  '/learn/$id': typeof LearnIdRoute
  '/puzzles/$id': typeof PuzzlesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analysis'
    | '/fair-play'
    | '/history'
    | '/learn'
    | '/login'
    | '/play'
    | '/profile'
    | '/puzzles'
    | '/settings'
    | '/stats'
    | '/variants'
    | '/api/rtc'
    | '/history/$id'
    | '/learn/$id'
    | '/puzzles/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analysis'
    | '/fair-play'
    | '/history'
    | '/learn'
    | '/login'
    | '/play'
    | '/profile'
    | '/puzzles'
    | '/settings'
    | '/stats'
    | '/variants'
    | '/api/rtc'
    | '/history/$id'
    | '/learn/$id'
    | '/puzzles/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analysis'
    | '/fair-play'
    | '/history'
    | '/learn'
    | '/login'
    | '/play'
    | '/profile'
    | '/puzzles'
    | '/settings'
    | '/stats'
    | '/variants'
    | '/api/rtc'
    | '/history/$id'
    | '/learn/$id'
    | '/puzzles/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalysisRoute: typeof AnalysisRoute
  FairPlayRoute: typeof FairPlayRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  VariantsRoute: typeof VariantsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-play': {
      id: '/fair-play'
      path: '/fair-play'
      fullPath: '/fair-play'
      preLoaderRoute: typeof FairPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/learn/$id': {
      id: '/learn/$id'
      path: '/$id'
      fullPath: '/learn/$id'
      preLoaderRoute: typeof LearnIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/puzzles/$id': {
      id: '/puzzles/$id'
      path: '/$id'
      fullPath: '/puzzles/$id'
      preLoaderRoute: typeof PuzzlesIdRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface LearnRouteChildren {
  LearnIdRoute: typeof LearnIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnIdRoute: LearnIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface PuzzlesRouteChildren {
  PuzzlesIdRoute: typeof PuzzlesIdRoute
}

const PuzzlesRouteChildren: PuzzlesRouteChildren = {
  PuzzlesIdRoute: PuzzlesIdRoute,
}

const PuzzlesRouteWithChildren =
  PuzzlesRoute._addFileChildren(PuzzlesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalysisRoute: AnalysisRoute,
  FairPlayRoute: FairPlayRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  VariantsRoute: VariantsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
